export const CONSTANT = {
    domainApi: process.env.NODE_ENV === "development" ? "https://okigwecreations.online/api/"  : "https://okigwecreations.online/api/", 
    token:'token',
    setPassword:'SetPassword',
    forgotPassword:'forgotPassword',
    resetPassword:'resetPassword',
    changePassword:'changePassword',
    logout:'logout',
    updateStatus:'updateStatus',
    loading:'loading',
    navigate:'navigate',
    set_State:'set_State',
    error:'error',
    setLoginPhase:'setLoginPhase',
    get_all_loan_request:'',
    get_repayment_schedule:'',
    request_for_loan:'',
    subscribe:'subscribe',
    
}