import React  from 'react';

export default function Privacy() {
 
  return (
      <div>
        <center><h3>Privacy Policy</h3></center>
        <p>Last  Updated November, 2022</p>
        <h1>Our Commitment to Protecting Your Privacy</h1>
<p>As a trusted advisor to our clients, Makolaa is committed to protecting your privacy. This notice outlines our policies and practices related to the sharing of personal financial information. We collect information about you to identify you when you are using our services and to offer you the appropriate services to help you achieve your financial goals.</p>
<p>We collect the following non-public personal information about you:</p>
<ul>
<li>Information you provide in forms to obtain products and services, such as your name, organisation, phone number and email.</li>
<li>Information you provide in applications such as your name, email and information included in your application documents such as your resume and cover letter.</li>
</ul>
<p>One of the ways we safeguard your privacy is by restricting access to your information to only those employees who need to know this information to provide you with the products and services you have requested. In addition, we maintain physical, electronic, and procedural safeguards that comply with federal standards.</p>
<p>We do not disclose any non-public personal information about our clients or former clients to anyone, except as permitted or required by law.</p>
<p>We may share non-public personal information with affiliated and non-affiliated third parties with which we contract to assist us in providing services to you (such as data processing, fraud prevention, regulatory and compliance, and operational support) or as permitted by law or with your consent. However, all affiliates and non-affiliated third parties are required to maintain the confidentiality of the client information we share with them. We do not sell your personal information to other companies for their independent marketing purposes.</p>
<p>We value the trust you place in our firm and in our employees. We understand that protecting your privacy is essential to maintaining your trust, and we commit that we will adhere to the above policies and practices.</p>
<h2>Social Media Plug-Ins</h2>
<p>We do not use plug-ins from social networks on our website. We only link our profile on the social networks Facebook, Twitter, LinkedIn to our website. Your data will not be retrieved by the social networks connected to our website.</p>
<h2>Analytical Tools</h2>
<p>In order to develop our website in line with customer needs we work with Google Analytics, a web analysis service of Google LLC. (<a href="https://about.google/intl/ng/" target="_blank" rel="noopener">https://about.google/intl/ng/</a>) (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA) to track usage on our website.</p>
<p>Google Analytics provide us with statistics to show us which pages on our website are visited most frequently and how long visitors spend on our site. We use this information to help us plan how we should improve the site.</p>
<p>Google Analytics uses a first-party cookie and JavaScript code to track the number of unique users of the site. It basically tells us whether we have a small number of regular visitors to the site or a large number of infrequent visitors. None of the information can be traced to an individual &ndash; we do not know who you are as a unique user, merely that there are a certain number of people using the site. The cookie only relates to what goes on in the Makolaa site and the information cannot be used for marketing on an individual basis.</p>
<p>The information generated by the cookies about your usage of this website such as</p>
<ul>
<li>browser type/ version,</li>
<li>used operating system,</li>
<li>referrer URL (the website visited before),</li>
<li>hostname of the accessing computer (IP address),</li>
<li>time of the server request,</li>
</ul>
<p>are transferred to a server belonging to Google located in the United States and saved there. This information is used to evaluate the usage of the website, to compile reports about the site activities and to render other services related to the usage of the website and the web usage for the purpose of market research and needs-based arrangement of these websites. Also, if necessary, this information will be transmitted to third parties if this is prescribed by law or insofar as third parties process these data by order. Under no circumstances, your IP address will be brought together with other data belonging to Google. The IP addresses will be anonymized so that an allocation is not possible (IP masking).</p>
<p>You can prevent the installation of cookies through the settings of the browser software; however, please note that this might cause some functions of this website not to function properly to you.</p>
<p>Furthermore, you can prevent the data (including your IP address) created by the cookie containing information about your usage of the website as well as the processing of this data by Google by downloading and installing a Browser Add-on (<a href="https://tools.google.com/dlpage/gaoptout?hl=com" target="_blank" rel="noopener">https://tools.google.com/dlpage/gaoptout?hl=com</a>).</p>
<p>Further information about data protection in connection with Google Analytics can be found in the Google Analytics Help section (<a href="https://support.google.com/analytics/answer/6004245?hl=en" target="_blank" rel="noopener">https://support.google.com/analytics/answer/6004245?hl=en</a>).</p>
<h2>Job Applications</h2>
<p>We process the data provided by you within your application for the implementation of the application procedure and, if necessary, of the recruitment procedure. To do this, we collect personal data from you including your name, email, curriculum vitae, cover letter and other information provided by you.</p>
<p>If you transmit your data by email, we process your email address for the purpose of the processing and for the purpose of contacting you.</p>
<p>Your personal application details are only collected, saved, processed and used for purposes that are associated with your interest in a current or future employment opportunity with us.</p>
<p>If we do not offer you a position as an employee, we will save the data provided by you for up to six months after the conclusion of the application procedure for the purpose of answering questions in connection with your application and its rejection.</p>
<p>This does not apply if statutory provisions are opposed to a deletion, if the longer storage is needed for the purpose of proof, or if we have your express agreement for a longer storage.</p>
      </div>  
     
  );
}


